[pytest]
;addopts = -vs --alluredir ./report/temp -p no:warnings --clean-alluredir
;
;testpaths = ./testcase/

addopts =
    --ignore="testcase/Business interface"
    --ignore="testcase/ProductManager"
    --ignore="testcase/Single interface"

filterwarnings =
    error
    ignore::UserWarning

python_files = test_*.py

python_classes = Test*

python_functions = test
